name: smart_fruit
description: Intelligent Fruit Recognition & Voice Assistant App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  # State Management (using Riverpod for scalability)
  flutter_riverpod: ^2.4.9
  
  # TFLite
  tflite_flutter: ^0.10.4
  image_picker: ^1.0.5
  image: ^4.1.3
  
  # Voice & Speech
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.1.0
  
  # API
  http: ^1.1.2
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  
  # UI Helpers
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/
    - assets/animations/
    - assets/fruits/
  
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
